### ISSUE TITLE
Java 11 user can compile and run Apache Beam pipeline

### ISSUE THREAD

**Issue by mschickensoup** [mwalenia/beam#15]

**Comment by pawelpasterz** [comment]
Depends on:

1. #60 
2. #61 
3. #62

**Comment by pawelpasterz** [comment]
As of June 1st:
All (except Java Precommit) precommit jobs are implemented and running continuously on jenkins.
`Java Precommit` job indicated some problems with beam itself, which should be solved. All issues gathered inside https://issues.apache.org/jira/browse/BEAM-10090

After discussion, task considered as done.
